version: '3.6'
services:
  vietlavel:
    image: nginx:1.15
    depends_on:
      - vietlavel-phpfpm
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8002:80"

  vietlavel-phpfpm:
    image: vietlavel:local
    volumes:
      - ./:/app
