version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1
  aws-ecr: circleci/aws-ecr@6.12.2

jobs:
  deploy:
    docker:
      - image: 'cimg/base:2020.01'
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: install_dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y jq gettext-base
      - run:
          name: deploy_image
          command: |
            chmod +x vit-deploy.sh
            ./vit-deploy.sh
            echo **** Deployment Done ****

workflows:
  build_push_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          context: demo
          # account-url: $AWS_ECR_ACCOUNT_URL
          # aws-access-key-id: $AWS_ACCESS_KEY_ID
          # aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          # region: $AWS_REGION
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 10m
          path: .
          profile-name: default
          repo: ${CIRCLE_PROJECT_REPONAME}
          skip-when-tags-exist: false
          tag: 'latest,${CIRCLE_SHA1}-${CIRCLE_BRANCH}'
      - deploy:
          context: demo
          requires:
            - aws-ecr/build-and-push-image